#!/bin/bash

# Check if at least two arguments are provided
if [ "$#" -lt 2 ]; then
    echo "Usage: $0 <docker-container-index> <cmd>"
    exit 1
fi

# Assign the arguments to variables
container_index=$1
shift
cmd=$@

# Get the container ID based on the provided index
container_id=$(docker ps -q | awk "NR==$container_index+1")

echo "ContainerID:" $container_id

# Check if the container ID was found
if [ -z "$container_id" ]; then
    echo "No container found at index $container_index"
    exit 1
fi

# Execute the command in the specified container
docker exec -it "$container_id" sh -c '$cmd'
