#!/bin/bash

machine_id=16657
host_id=81587
end_date='7 May 2024 15:00' # Subtracted 3 hours for Local time
num_gpus=4
discount=0.01
records=3

retrieve_average_price() {
    # Set the search criteria for available offers
    search_criteria="gpu_name=RTX_4090 num_gpus="$num_gpus" host_id!="$host_id" inet_up>=100 reliability>=0.95 duration>3"

    #vastai search offers "$search_criteria" -o dph

    # Execute the vastai search with the given criteria
    # Sort offers by dollars per hour and disable bundling
    # then, pass the output through awk for processing
    average_price=$(vastai search offers "$search_criteria" -o dph | awk '
        BEGIN {
            # Initialize variables to store the total and count of relevant offerings
            total=0
            count=0
        }
        NR>1 && NR<='$((records+1))' {
            # Take first few records, accumulate the Price values and increment count
            total += $9
            count++
        }
        END {
            printf total/count/'$num_gpus'
        }'
    )

    adjusted_price=$(printf "%.6f" $(echo "$average_price - $discount" | bc -l))
    total_price_avg=$(printf "%.6f" $(echo "$average_price * $num_gpus" | bc -l))
    total_price_adj=$(printf "%.6f" $(echo "$adjusted_price * $num_gpus" | bc -l))

    echo "Average Price: $average_price, Total Price: $(echo "$average_price * $num_gpus" | bc -l)"
    echo "Adjusted Price: $adjusted_price, Total Price: $(echo "$adjusted_price * $num_gpus" | bc -l)"
}

# Set adjusted price
update_vastai_price() {
    local price_gpu=$1
    unix_date=$(date -d "$end_date" +%s)
    vastai list machine $machine_id --price_gpu $price_gpu --price_disk 0.4 --price_inetu 0.0048828125 --price_inetd 0.0048828125 --discount_rate 0 --min_chunk $num_gpus --end_date $unix_date
}

retrieve_average_price
update_vastai_price $adjusted_price
